### ISSUE TITLE
✨ [Feature request] - Add an example notebook for Seshat API that shows comparisons between variables

### ISSUE THREAD

**Issue by edwardchalstrey1** [Seshat-Global-History-Databank/seshat_api#16]
### Description of Improvement

Imagine we are interested in looking at the relationship several of Seshat's data variables, to see which appear to be correlated in the number of polities that have them recorded as "Present".

For example, the relationship between a transport infrastructure variable such as "Road" and a profession variable like "Professional soldier". The hypothesis could be that the polities with professional soldiers need roads for them to move on, so there should be a strong correlation between the number of polities with soldiers and the number of polities with roads in any given year.

We could compare this to some other variables that we believe less likely to be correlated.

### TODOs:
- [x] Add a correlation coefficient
- [x] Refactor `get_frequencies` to accept the class names instead of the lowercase variables
- ~~Add an arg to `get_variable_classes` that allows you to specify absent/present vars only~~
- [x] Make `get_variable_classes` list fully alphabetical or better still split by app/db
- [x] Any other cool variable combos
    - Add a super obvious ones like Judge vs court 
- [x] Add `scipy` to the notebook requirements, then test the notebook requirements/env setup and update requirements.txt & README
- [x] Test `get_frequencies` and other new functions
- [x] Set up pytest
- [x] Set up GH actions
- [x] Add `value` argument to `get_frequencies` so you can get "absent" as well as "present", but you could also pass in "Spanish" if we were looking at Language for example
- [x] Refactor and comment get_frequencies
    - Might want to move the importer step as a separate function
    - Explain in the notebook too
- [x] Add suggested extra tasks to the bottom of variables and camels notebooks
- [x] Rename both notebooks with sensible names
- [x] Package version increment
- ~~Document the new functions~~ - does the API package need it's own auto-generated docs? If so, open an issue for this
    - I think this overkill for now with the examples being there. We might want some proper docs if a lot of functions get added with various data transformations, but until that is definitely the case, I'm not sure its needed.
- [x] #10 
- [x] #11 
- [x] Set up pre-commit that clears the notebook output (or make the decision to save the output)

### Notes

- There is no easy way to get a list of the Seshat variables in lower case, because these are the specific attributes of the different model classes which are named similarly but with the capitalisation and underscore convention

### Definition of Done

- [x] The feature has been developed on a feature branch.
- [x] A pull request has been created for the feature branch to be merged into the main branch.

**Comment by edwardchalstrey1** [comment]
Working on the `extra-tasks` branch
